#!/usr/bin/env php

<?php
require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Neptunia\Config\Command\CreateUserCommand;

$application = new Application();
// if ($argv[1] == "serve") {
//     exec("php -S localhost:8888 -t views/");
// }// ...

$application->add(new CreateUserCommand());
$application->run();
